### ISSUE TITLE
腾讯滑块问题

### ISSUE THREAD

**Issue by zqq993** [loyalist16/components#1]
大佬你好，在找腾讯滑块资料时偶然发现您的代码，但是看了下好像没写完，有最新的代码更新嘛。

**Comment by 15197619286** [comment]
> 大佬你好，在找腾讯滑块资料时偶然发现您的代码，但是看了下好像没写完，有最新的代码更新嘛。

**Comment by loyalist16** [comment]
我这就是新版本的滑块，但是我目前跟不出来它其中collect加密字段如何实现的，这个字段代表的应该就是滑块轨迹，其所在的tdc.js文件一直动态变化，目前能力还解决不了这一步ᥬ😂᭄



---原始邮件---
发件人: "15197619286"<notifications@github.com&gt;
发送时间: 2021年3月1日(周一) 上午9:44
收件人: "loyalist16/components"<components@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [loyalist16/components] 腾讯滑块问题 (#1)




 
大佬你好，在找腾讯滑块资料时偶然发现您的代码，但是看了下好像没写完，有最新的代码更新嘛。如果没写完，我这边找到另外一个大佬写的可运行demo可以参考，https://github.com/lijz36/CaptcheSpider。但是我的目标地址套用他的代码不行，他说是腾讯滑块已经改了
